### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by georgobermayrsaf** [atoms-studio/nuxt-swiftsearch#10]
I implemented routing as described in https://nuxt-swiftsearch.netlify.app/routing.
However when I select any refinement the Url becomes `/category?INDEX=[object+Object]` and the refinement is not selected. What am I missing here?

**Comment by georgobermayrsaf** [comment]
Thank you, @Rigo-m ! It seems the issue resolved on its own, seems to work fine now :-)

**Comment by Rigo-m** [comment]
Maybe you just had to reload the application after adding router.options.ts :) 
Also: be mindful of a problem handling query strings with nuxt 3.11, which is either not present in 3.10 or will be resolved in 3.12
