### ISSUE TITLE
Issues with useAisRouter and backward navigation

### ISSUE THREAD

**Issue by georgobermayrsaf** [atoms-studio/nuxt-swiftsearch#13]
I'm having issues with useAisRouter and backward / forward navigation in the browser.

- Open a page with a `AisInstantSearch` component on it, that has routing enabled with `useAisRouter()`
- Do some filtering to have the URL change, for instance: `http://localhost:3000/tickets/klassik/?local_PERFORMANCES%5BrefinementList%5D%5Bvenue.city%5D%5B0%5D=M%C3%BCnchen&local_PERFORMANCES%5Btoggle%5D%5Bis_available%5D=true`. 
- Click on one of the filter results to open another page. The link is built with `NuxtLink` component. The new address in the browser bar is then e.g. `http://localhost:3000/event/some-event/`
- Hit the browser back button
- The addresss in the browser bar changes to `http://localhost:3000/event/some-event/?local_PERFORMANCES%5Btoggle%5D%5Bis_available%5D=true` which is a mixture of the old and the new URL and also nothing happens. 
- In the network tab I can see some requests to Algolia queries and events API endpoints, but nothing more. Nothing from Nuxt is triggered.
- If I hit the browser back button one more time I get to `http://localhost:3000/tickets/klassik/?local_PERFORMANCES%5BrefinementList%5D%5Bvenue.city%5D%5B0%5D=M%C3%BCnchen&local_PERFORMANCES%5Btoggle%5D%5Bis_available%5D=true` and the page is also refreshing.

I'm not able to reproduce this in every try and also there are other quirks with the router sometimes that are a bit unpredictable. 

Can you confirm these issues on your end?

**Comment by Rigo-m** [comment]
I can confirm on my end. Would you mind trying v0.8.0?

**Comment by georgobermayrsaf** [comment]
Thank you @Rigo-m , that was quick! Yes, looks good on my end. Backward/Forward navigation seems to be smooth now 👍
