### ISSUE TITLE
Issue with use state keys in filters

### ISSUE THREAD

**Issue by glennjacobs** [atoms-studio/nuxt-swiftsearch#20]
We’re building an online store with Nuxt and using this package for our category pages. Each category requires its own distinct instance of Algolia search.

To achieve this, we’ve utilised the `:instance-key` prop on the `<ais-instant-search>` component, which ensures each page gets its own separate instance.

However, the filter components, such as those created using useAisRefinementList, have a static key hardcoded currently (see [this line](https://github.com/atoms-studio/nuxt-swiftsearch/blob/main/src/runtime/composables/useAisRefinementList.ts#L12)). This causes the filters to behave incorrectly when switching between pages in our app.

I’ve tested a workaround by incorporating the instance ID into the state key, and it resolves the issue.

I plan to work on a PR to address this properly but would appreciate any feedback you have, especially if you have a preferred approach for implementing this fix.

**Comment by Rigo-m** [comment]
Hi glenn! Hope you are enjoying swiftsearch!
I'll take a quick look at the pr, thanks!

**Comment by Rigo-m** [comment]
As a side note: why does each category require its own instant search instance? This can be quite heavy on user's memory. How many category pages do you have in your website?

**Comment by Rigo-m** [comment]
Released in 0.8.2, thanks for the patience!

**Comment by glennjacobs** [comment]
> Released in 0.8.2, thanks for the patience!

Amazing, many thanks again :)
