### ISSUE TITLE
Multiple useAisCurrentRefinements

### ISSUE THREAD

**Issue by LoMonacoSalvatore** [atoms-studio/nuxt-swiftsearch#4]
It would be nice to have the possibility to add multiple `useAisCurrentRefinements` in the Instantsearch config.
Same behaviour of `useAisRefinementList` matching by **attribute** the component in page.

tech notes:
Check if `useAisCurrentRefinements` is considered as an array on the `Instantsearch state`

**Comment by Met96** [comment]
Available since 0.4.4
